source 'https://rubygems.org'
ruby '2.1.1'
gem 'rails', '4.2.0.beta1'
gem 'sass-rails', '~> 5.0.0.beta1'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'rails-html-sanitizer', '~> 1.0'
group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0.0.beta2'
  gem 'spring'
end
gem 'bootstrap-sass'
gem 'figaro', '>= 1.0.0.rc1'
gem 'high_voltage'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'pg'
gem 'pundit'
gem 'simple_form'
gem 'thin'
gem 'arel', '6.0.0.beta2'
gem 'gmaps4rails'
gem 'underscore-rails'
gem 'geocoder'
gem 'yelp'
group :development do
  gem 'better_errors'
  gem 'binding_of_caller', :platforms=>[:mri_21]
  gem 'quiet_assets'
  gem 'rails_layout'
  gem 'spring-commands-rspec'
end
group :development, :test do
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'pry-rails'
  gem 'pry-rescue'
  gem 'rspec-rails'
  gem 'rubocop'
end
group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'selenium-webdriver'
end
